version: '2'
services:
  redis-server:
    image: "redis:alpine"
    container_name: redis_cache
    command: redis-server --appendonly yes
    ports:
      - "9000:6379"
    expose:
      - 6379
    restart:
      always
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge